project:
  name: kotlin-mpp-library
  package: com.meowbox.library
  group: com.meowbox
  version: 1.0
dependencies:
  agp: 7.0.4
  compose: 1.2.0-alpha01-dev675
  kotlin: 1.6.21
  kotlinx_coroutines: 1.6.1
  kotlinx_datetime: 0.3.2
  realm_library: 0.10.2
  realm: 0.10.2
publishing:
  repo: https://maven.pkg.github.com/tylergannon/polestar-ephemeris
android:
  sdk_path: /Users/tyler/Library/Android/sdk
